#!/usr/local/bin/task --taskfile

apiVersion: projects/v1
kind: mxk:ydt.reposet.items

metadata:
  name: reposet

# --- task include part
version: "3"
includes:
  reposet: ../_infra/reposet_pack/reposet.tasks.yml

vars:
  _taskfile_: reposet.info.yml
  reposet__conf_map: __repos:reposet.info.yml@vars.reposet_items_yaml
  reposet_items_yaml: |-
    spur_py:
      name: spur_py
      subdir: .
      dirname: ./spur_py
      branch: master
      remote_origin_url: https://github.com/ydtools/spur.py.git
    s3path:
      name: s3path
      subdir: .
      dirname: ./s3path
      branch: master
      remote_origin_url: https://github.com/ydtools/s3path.git
      
tasks:
  default:
    silent: true
    cmds: [{task: reposet:info}]
