# https://taskfile.dev

version: '3'
includes: 
  reposet: ../../_infra/reposet_pack/reposet.tasks.yml
vars:
  reposet__conf_map: __repos:reposet.info.yml@vars.reposet_items_yaml

tasks:
  default:
    cmds:
      - task -l | true
    silent: true
